import React, { Fragment } from 'react'
import PropTypes from 'prop-types';
import './WhatWeDo.css';
import solar500w from '../../../assets/solar system image-500w.png'
import battery1400w from '../../../assets/battery system - upload seperate imagefor each option - not one file for all-1400w.png'
import evCharger1400w from '../../../assets/ev charger - smart charger-1400w.jpg'

const WhatWeDo = (props) => {
    return (
        <div className="features1-layout251 thq-section-padding">
            <div className="features1-max-width thq-section-max-width">
                <div className="thq-flex-row features1-section-title">
                    <div className="features1-column thq-flex-column">
                        <h2 className="features1-text1 thq-heading-2">
                            {props.sectionTitle ?? (
                                <Fragment>
                                    <span className="features1-text3">WHAT WE DO</span>
                                </Fragment>
                            )}
                        </h2>
                    </div>
                </div>
                <div className="features1-content1">
                    <div className="features1-row thq-flex-row">
                        <div className="features1-feature1 thq-flex-column">
                            <img
                                alt={props.feature1ImageAlt}
                                src={solar500w}
                                className="thq-img-ratio-4-3 features1-feature1-image"
                            />
                            <div className="features1-content2 thq-flex-column">
                                <h3 className="features1-feature1-title thq-heading-3">
                                    {props.feature1Title ?? (
                                        <Fragment>
                                            <span className="features1-text5">
                                                Solar Panels Installation
                                            </span>
                                        </Fragment>
                                    )}
                                </h3>
                                <span className="thq-body-small">
                                    {props.feature1Description ?? (
                                        <Fragment>
                                            <span className="features1-text7">
                                                Efficient solar panels installed to harness the power of
                                                the sun and reduce your reliance on traditional
                                                electricity sources.
                                            </span>
                                        </Fragment>
                                    )}
                                </span>
                            </div>
                        </div>
                        <div className="features1-feature2 thq-flex-column">
                            <img
                                alt={props.feature2ImageAlt}
                                src={battery1400w}
                                className="thq-img-ratio-4-3 features1-feature2-image"
                            />
                            <div className="features1-content3 thq-flex-column">
                                <h3 className="features1-feature2-title thq-heading-3">
                                    {props.feature2Title ?? (
                                        <Fragment>
                                            <span className="features1-text8">
                                                Battery Storage Solutions
                                            </span>
                                        </Fragment>
                                    )}
                                </h3>
                                <span className="thq-body-small">
                                    {props.feature2Description ?? (
                                        <Fragment>
                                            <span className="features1-text6">
                                                Store excess energy generated by your solar panels for
                                                use during peak hours or in case of power outages.
                                            </span>
                                        </Fragment>
                                    )}
                                </span>
                            </div>
                        </div>
                        <div className="features1-feature3 thq-flex-column">
                            <img
                                alt={props.feature3ImageAlt}
                                src={evCharger1400w}
                                className="thq-img-ratio-4-3 features1-feature3-image"
                            />
                            <div className="features1-content4 thq-flex-column">
                                <h3 className="features1-feature3-title thq-heading-3">
                                    {props.feature3Title ?? (
                                        <Fragment>
                                            <span className="features1-text2">
                                                EV Charger Installation
                                            </span>
                                        </Fragment>
                                    )}
                                </h3>
                                <span className="thq-body-small">
                                    {props.feature3Description ?? (
                                        <Fragment>
                                            <span className="features1-text4">
                                                Charge your electric vehicle at home with our EV charger
                                                installation services, making sustainable transportation
                                                even more convenient.
                                            </span>
                                        </Fragment>
                                    )}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="features1-actions"></div>
            </div>
        </div>
    )
}

WhatWeDo.defaultProps = {
    feature3Title: undefined,
    sectionTitle: undefined,
    feature3Description: undefined,
    feature1Title: undefined,
    feature2Description: undefined,
    feature1Description: undefined,
    feature3ImageAlt: 'EV Charger Installation Image',
    feature1ImageAlt: 'Solar Panels Installation Image',
    feature2Title: undefined,
    feature2ImageAlt: 'Battery Storage Solutions Image',
}

WhatWeDo.propTypes = {
    feature3Title: PropTypes.element,
    sectionTitle: PropTypes.element,
    feature3Description: PropTypes.element,
    feature1Title: PropTypes.element,
    feature2Description: PropTypes.element,
    feature1Description: PropTypes.element,
    feature3ImageAlt: PropTypes.string,
    feature1ImageAlt: PropTypes.string,
    feature2Title: PropTypes.element,
    feature2ImageAlt: PropTypes.string,
}

export default WhatWeDo;
