import React from "react";
import { Link, useNavigate } from "react-router-dom";

const HOME = () => {
  const navigate = useNavigate();

  const handleOrderNowClick = () => {
    navigate("/product");
  };

  return (
    <div className="flex flex-col min-h-screen w-full bg-white">
      {/* NAVBAR */}
      <header className="sticky top-0 z-50 bg-white shadow">
        <div className="max-w-6xl mx-auto flex items-center justify-between py-4 px-4 md:px-0">
          {/* Left Section: Logo */}
          <div className="flex items-center space-x-2">
            <img
              src="/logo%202-1400w.png"
              alt="Absolute Energy Logo"
              className="h-10 w-auto"
            />
            <span className="font-bold text-xl tracking-wide">ABSOLUTE ENERGY</span>
          </div>
          {/* Middle Section: Nav Links */}
          <nav className="hidden md:flex items-center space-x-8">
            <Link
              to="/"
              className="text-gray-700 hover:text-orange-600 transition-colors"
            >
              HOME
            </Link>
            <Link
              to="/faq"
              className="text-gray-700 hover:text-orange-600 transition-colors"
            >
              FAQ
            </Link>
            <Link
              to="/learn"
              className="text-gray-700 hover:text-orange-600 transition-colors"
            >
              LEARN
            </Link>
            <Link
              to="/contact"
              className="text-gray-700 hover:text-orange-600 transition-colors"
            >
              CONTACT
            </Link>
          </nav>
          {/* Right Section: Order Now button */}
          <button
            onClick={handleOrderNowClick}
            className="hidden md:inline-block bg-orange-500 text-white font-semibold px-4 py-2 rounded hover:bg-orange-600 transition-colors"
          >
            ORDER NOW
          </button>
          {/* Mobile Menu (optional) */}
          <div className="md:hidden">
            {/* Add a hamburger menu or any mobile nav logic if you need it */}
          </div>
        </div>
      </header>

      {/* HERO SECTION */}
      <section className="bg-white text-center py-10 md:py-16 px-4">
        <div className="max-w-2xl mx-auto">
          <h1 className="text-3xl md:text-5xl font-bold mb-4 leading-tight">
            Simplifying Your Future Energy Needs
          </h1>
          <p className="text-gray-600 mb-6">
            Order solar panels, batteries, and EV chargers with ease to power
            your home sustainably.
          </p>
          <button
            onClick={handleOrderNowClick}
            className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded font-semibold transition-colors"
          >
            ORDER NOW
          </button>
        </div>
      </section>

      {/* ORANGE SEPARATOR BAR */}
      <div className="w-full h-6 bg-orange-500"></div>

      {/* WHAT WE DO */}
      <section className="py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-8 text-orange-600">
            WHAT WE DO
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Card 1 */}
            <div className="flex flex-col items-center text-center">
              <img
                src="/solar%20system%20image-1400w.png"
                alt="Solar Panels"
                className="h-52 w-auto object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Solar Panels Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Efficient solar panels installed to harness the power of the sun
                and reduce your reliance on traditional electricity sources.
              </p>
            </div>
            {/* Card 2 */}
            <div className="flex flex-col items-center text-center">
              <img
                src="/battery%20system%20-%20upload%20seperate%20imagefor%20each%20option%20-%20not%20one%20file%20for%20all-300h.png"
                alt="Battery Storage"
                className="h-52 w-auto object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Battery Storage Solutions
              </h3>
              <p className="text-gray-600 max-w-sm">
                Store excess energy generated by your solar panels for use
                during peak hours or in case of power outages.
              </p>
            </div>
            {/* Card 3 */}
            <div className="flex flex-col items-center text-center">
              <img
                src="/ev%20charger%20-%20smart%20charger-300h.jpg"
                alt="EV Charger"
                className="h-52 w-auto object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                EV Charger Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Charge your electric vehicle at home with our EV charger
                installation services, making sustainable transportation even
                more convenient.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* HOW WE DO IT */}
      <section className="py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-6">
            HOW WE DO IT
          </h2>
          <div className="flex flex-col md:flex-row md:justify-between md:items-center mb-8">
            <p className="text-gray-600 md:w-1/2 mb-4 md:mb-0 text-center md:text-left">
              Discover the power of our straightforward system
            </p>
            <div className="text-center md:text-right">
              <button
                onClick={handleOrderNowClick}
                className="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded font-semibold transition-colors"
              >
                ORDER NOW
              </button>
            </div>
          </div>

          {/* Steps Container */}
          <div className="space-y-6">
            {/* Step 1 */}
            <div className="relative p-4 bg-white shadow rounded border-l-4 border-orange-500">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                01
              </div>
              <h3 className="text-xl font-semibold mb-1">SELECTION</h3>
              <p className="text-gray-600">
                Configure your system in our tool under "Order Now". Select the
                options that suit your needs.
              </p>
            </div>
            {/* Step 2 */}
            <div className="relative p-4 bg-orange-50 shadow rounded border-l-4 border-orange-500">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                02
              </div>
              <h3 className="text-xl font-semibold mb-1">DEPOSIT &amp; SCHEDULE</h3>
              <p className="text-gray-600">
                Our professional team will handle the installation of solar
                panels, batteries, and EV chargers at your convenience,
                ensuring a seamless setup process.
              </p>
            </div>
            {/* Step 3 */}
            <div className="relative p-4 bg-white shadow rounded border-l-4 border-orange-500">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                03
              </div>
              <h3 className="text-xl font-semibold mb-1">DESIGN CONFIRMATION</h3>
              <p className="text-gray-600">
                Once installed, we will activate your solar panels, batteries,
                and EV chargers to start harnessing clean energy for your home.
              </p>
            </div>
            {/* Step 4 */}
            <div className="relative p-4 bg-orange-50 shadow rounded border-l-4 border-orange-500">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                04
              </div>
              <h3 className="text-xl font-semibold mb-1">INSTALLATION</h3>
              <p className="text-gray-600">
                Professional installation of selected products by certified
                technicians to ensure optimal performance.
              </p>
            </div>
            {/* Step 5 */}
            <div className="relative p-4 bg-white shadow rounded border-l-4 border-orange-500">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                05
              </div>
              <h3 className="text-xl font-semibold mb-1">ENJOY THE SAVINGS</h3>
              <p className="text-gray-600">
                Start enjoying the benefits of clean energy and savings on your
                electricity bills.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA BANNER */}
      <section className="bg-orange-500 text-white text-center py-8 px-4">
        <div className="max-w-5xl mx-auto">
          <h3 className="text-2xl md:text-3xl font-bold mb-3">
            READY TO SIMPLIFY YOUR HOME ENERGY NEEDS?
          </h3>
          <p className="mb-5 max-w-3xl mx-auto">
            Explore our range of products and services to start saving energy and
            money today.
          </p>
          <button
            onClick={handleOrderNowClick}
            className="bg-white text-orange-600 font-semibold px-6 py-3 rounded hover:bg-orange-100 transition-colors"
          >
            ORDER NOW
          </button>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section className="py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-6">
            Testimonials
          </h2>
          <p className="text-center text-gray-600 max-w-2xl mx-auto mb-8">
            Read what our customers have to say about their experience with our home
            energy solutions.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {/* Testimonial 1 */}
            <div className="p-6 bg-gray-50 rounded shadow">
              <h3 className="font-bold">John Doe</h3>
              <p className="text-sm text-gray-500">Homeowner</p>
              <p className="text-gray-700 mt-2">
                I installed solar panels from this company, and I couldn't be
                happier with the results. My energy bills have significantly
                decreased, and I feel good about reducing my carbon footprint.
              </p>
            </div>
            {/* Testimonial 2 */}
            <div className="p-6 bg-gray-50 rounded shadow">
              <h3 className="font-bold">Jane Smith</h3>
              <p className="text-sm text-gray-500">Environmental Advocate</p>
              <p className="text-gray-700 mt-2">
                The battery system I purchased has been a game-changer for me.
                It's reliable, efficient, and has given me peace of mind during
                power outages.
              </p>
            </div>
            {/* Testimonial 3 */}
            <div className="p-6 bg-gray-50 rounded shadow">
              <h3 className="font-bold">David Johnson</h3>
              <p className="text-sm text-gray-500">Electric Vehicle Owner</p>
              <p className="text-gray-700 mt-2">
                I got an EV charger installed at my home, and it has made
                charging my electric car so convenient. The installation was
                quick, and the charger works flawlessly.
              </p>
            </div>
            {/* Testimonial 4 */}
            <div className="p-6 bg-gray-50 rounded shadow">
              <h3 className="font-bold">Sarah Lee</h3>
              <p className="text-sm text-gray-500">Renewable Energy Enthusiast</p>
              <p className="text-gray-700 mt-2">
                I highly recommend this company for all your home energy needs.
                Their products are top-notch, and their customer service is
                exceptional.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-white border-t border-gray-200 mt-auto">
        <div className="max-w-6xl mx-auto py-6 px-4 md:px-0 flex flex-col md:flex-row md:items-center md:justify-between">
          {/* Footer Logo/Name */}
          <div className="flex items-center space-x-2 mb-4 md:mb-0">
            <img
              src="/logo%202-1400w.png"
              alt="Footer Logo"
              className="h-8 w-auto"
            />
            <span className="font-bold text-lg tracking-wide">ABSOLUTE ENERGY</span>
          </div>
          {/* Footer Nav */}
          <nav className="flex flex-col sm:flex-row sm:items-center sm:space-x-6 text-sm text-gray-700">
            <Link to="/" className="hover:underline mb-2 sm:mb-0">
              HOME
            </Link>
            <Link to="/learn" className="hover:underline mb-2 sm:mb-0">
              LEARN
            </Link>
            <Link to="/faq" className="hover:underline mb-2 sm:mb-0">
              FAQ
            </Link>
            <Link to="/product" className="hover:underline mb-2 sm:mb-0">
              ORDER NOW
            </Link>
            <Link to="/contact" className="hover:underline">
              Contact Us
            </Link>
          </nav>
        </div>
        <div className="max-w-6xl mx-auto pb-6 px-4 md:px-0 flex flex-col-reverse md:flex-row items-center justify-between text-gray-500 text-sm">
          <span className="mt-2 md:mt-0">© 2024 ABSOLUTE ENERGY</span>
          <div className="flex space-x-4">
            <Link to="/privacy" className="hover:underline">
              Privacy Policy
            </Link>
            <Link to="/terms" className="hover:underline">
              Terms and Conditions
            </Link>
            <Link to="/cookies" className="hover:underline">
              Cookies Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HOME;
