import React from "react";
import { useNavigate } from "react-router-dom";
import LandingPageHeader from "./LandingPageHeader"; // Import the new header component
import logo1400w from "../assets/logo 2-1400w.png";
import solar500w from "../assets/solar system image-500w.png"
import solar1400w from "../assets/solar system image-1400w.png"
import battery1400w from "../assets/battery system - upload seperate imagefor each option - not one file for all-1400w.png"
import evCharger1400w from "../assets/ev charger - smart charger-1400w.jpg"
import LandingPageFooter from "./LandingPageFooter";


const HOME = () => {
  const navigate = useNavigate();

  const handleOrderNowClick = () => {
    navigate("/product");
  };

  return (
    <div className="flex flex-col min-h-screen w-full bg-white">
      {/* Use the LandingPageHeader component */}
      <LandingPageHeader />

      {/* HERO SECTION */}
      <section className="bg-white text-center py-10 md:py-16 px-4">
        <div className="max-w-2xl mx-auto">
          <img src={logo1400w} alt="" />
          <h1 className="text-3xl md:text-3xl font-bold mb-4 py-4 leading-tight">
            Simplifying Your Future Energy Needs
          </h1>
          <p className="text-lg text-gray-600 mb-6">
            Order solar panels, batteries, and EV chargers with ease to power
            your home sustainably.
          </p>
          <button
            onClick={handleOrderNowClick}
            className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded-full font-semibold transition-colors"
          >
            ORDER NOW
          </button>
        </div>
      </section>

      {/* ORANGE SEPARATOR BAR */}
      <div
        className="w-full h-32 bg-gradient-to-b from-orange-500 to-orange-600 border-t-[12px] border-b-[12px] border-amber-900 shadow-[inset_0_2px_4px_rgba(0,0,0,0.2)]"
      ></div>


      {/* WHAT WE DO */}
      <section className="py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-start mb-8 text-orange-700">
            WHAT WE DO
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Card 1 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={solar500w}
                alt="Solar Panels"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Solar Panels Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Efficient solar panels installed to harness the power of the sun
                and reduce your reliance on traditional electricity sources.
              </p>
            </div>
            {/* Card 2 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={battery1400w}
                alt="Battery Storage"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Battery Storage Solutions
              </h3>
              <p className="text-gray-600 max-w-sm">
                Store excess energy generated by your solar panels for use
                during peak hours or in case of power outages.
              </p>
            </div>
            {/* Card 3 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={evCharger1400w}
                alt="EV Charger"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                EV Charger Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Charge your electric vehicle at home with our EV charger
                installation services, making sustainable transportation even
                more convenient.
              </p>
            </div>
          </div>
        </div>
      </section>



      {/* HOW WE DO IT */}
      <section className="relative py-10 md:py-16 px-4 text-orange-700 bg-white">
        {/* Heading */}
        <div className="max-w-6xl mx-auto text-center mb-10">
          <h2 className="text-2xl md:text-3xl font-bold">HOW WE DO IT</h2>
        </div>

        {/* Grid Layout */}
        <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10">
          {/* Left Column: Text and Button */}
          <div className="flex flex-col justify-start space-y-6">
            <p className="text-gray-600 text-lg text-center lg:text-left">
              Discover the power of our straightforward system
            </p>
            <div className="text-center lg:text-left">
              <button
                onClick={handleOrderNowClick}
                className="relative group overflow-hidden bg-orange-500 text-white font-semibold px-6 py-1 rounded-full border-2 border-orange-500 transition-all duration-300"
              >
                {/* Sliding Background */}
                <span className="absolute inset-[-1px] bg-black transform -translate-x-full group-hover:translate-x-0 transition-transform duration-300 ease-out"></span>

                {/* Button Text */}
                <span className="relative">ORDER NOW</span>
              </button>
            </div>
          </div>

          {/* Right Column: Cards */}
          <div className="space-y-10">
            {/* Step 1 */}
            <div className=" sticky top-[88px] z-10 p-6 bg-white shadow-md rounded-md transform [rotate:-3deg] h-48 w-full">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">01</div>
              <h3 className="text-xl font-semibold mb-2">SELECTION</h3>
              <p className="text-gray-600">
                Configure your system in our tool under "Order Now". Select the options that suit your needs.
              </p>
            </div>

            {/* Step 2 */}
            <div className=" sticky top-[88px] z-20 p-6 bg-orange-100 shadow-md rounded-md transform [rotate:3deg] h-48 w-full">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">02</div>
              <h3 className="text-xl font-semibold mb-2 text-black">DEPOSIT & SCHEDULE</h3>
              <p className="text-gray-700">
                Our professional team will handle the installation of solar panels, batteries, and EV chargers at your
                convenience, ensuring a seamless setup process.
              </p>
            </div>

            {/* Step 3 */}
            <div className=" sticky top-[88px] z-30 p-6 bg-white shadow-md rounded-md transform [rotate:-3deg] h-48 w-full">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">03</div>
              <h3 className="text-xl font-semibold mb-2">DESIGN CONFIRMATION</h3>
              <p className="text-gray-600">
                Once installed, we will activate your solar panels, batteries, and EV chargers to start harnessing clean
                energy for your home.
              </p>
            </div>

            {/* Step 4 */}
            <div className=" sticky top-[88px] z-40 p-6 bg-orange-100 shadow-md rounded-md transform [rotate:3deg] h-48 w-full">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">04</div>
              <h3 className="text-xl font-semibold mb-2">INSTALLATION</h3>
              <p className="text-gray-600">
                Professional installation of selected products by certified technicians to ensure optimal performance.
              </p>
            </div>

            {/* Step 5 */}
            <div className=" sticky top-[88px] z-50 p-6 bg-white shadow-md rounded-md transform [rotate:-3deg] h-48 w-full">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">05</div>
              <h3 className="text-xl font-semibold mb-2">ENJOY THE SAVINGS</h3>
              <p className="text-gray-600">
                Start enjoying the benefits of clean energy and savings on your electricity bills.
              </p>
            </div>
          </div>
        </div>
      </section>


      <section className="relative py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto text-center mb-10">
          <h2 className="text-2xl md:text-3xl font-bold text-orange-700">OUR PROMISE</h2>
        </div>
        <div className="relative max-w-6xl mx-auto">
          {/* Top Decorative Line */}
          <div className="absolute -top-3 left-0 right-0 h-10 bg-orange-200 transform rotate-1 rounded-t-lg"></div>

          {/* Main Card */}
          <div className="relative bg-orange-600 text-white rounded-lg shadow-lg p-8 z-10 transform rotate-[-1deg]">
            <h3 className="text-2xl font-bold mb-4">READY TO SIMPLIFY YOUR HOME ENERGY NEEDS?</h3>
            <p className="text-lg mb-6">
              Explore our range of products and services to start saving energy and money today.
            </p>
            <button
              onClick={handleOrderNowClick}
              className="relative group overflow-hidden bg-black text-white font-semibold px-6 py-3 rounded-full border-2 border-black transition-all duration-300"
            >
              {/* Sliding Background */}
              <span className="absolute inset-0 bg-orange-500 transform -translate-x-full group-hover:translate-x-0 transition-transform duration-300 ease-out"></span>
              {/* Button Text */}
              <span className="relative z-10">ORDER NOW</span>
            </button>
          </div>

          {/* Bottom Decorative Line */}
          <div className="absolute -bottom-3 left-0 right-0 h-10 bg-orange-200 transform rotate-1 rounded-b-lg"></div>
        </div>
      </section>


      {/* Testimonials wrapper */}
      <section className="py-10 md:py-16 px-4 bg-white">
        {/* Heading */}
        <div className="text-center mb-10">
          <h2 className="text-3xl font-bold text-black">Testimonials</h2>
          <p className="text-lg text-gray-600">
            Read what our customers have to say about their experience with our home energy solutions.
          </p>
        </div>

        {/* Testimonials */}
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
          {/* Testimonial 1 */}
          <div className="relative group bg-white shadow-lg rounded-lg p-6 transition-all duration-300 hover:shadow-2xl hover:-translate-y-2">
            {/* Background Decorative Shape */}
            <div
              className="absolute -top-2 -left-2 w-full h-full bg-orange-100 transform rotate-1 rounded-lg z-0 group-hover:rotate-3 transition-transform duration-300"
              aria-hidden="true"
            ></div>
            <div className="relative z-10">
              <div className="flex items-center mb-4">
                <img
                  src="https://via.placeholder.com/40"
                  alt="John Doe"
                  className="w-10 h-10 rounded-full mr-4"
                />
                <div>
                  <h3 className="text-lg font-bold text-black">John Doe</h3>
                  <p className="text-sm text-gray-500">Homeowner</p>
                </div>
              </div>
              <p className="text-gray-600">
                I installed solar panels from this company, and I couldn't be happier with the results. My energy bills have significantly decreased, and I feel good about reducing my carbon footprint.
              </p>
            </div>
          </div>

          {/* Testimonial 2 */}
          <div className="relative group bg-white shadow-lg rounded-lg p-6 transition-all duration-300 hover:shadow-2xl hover:-translate-y-2">
            <div
              className="absolute -top-2 -left-2 w-full h-full bg-orange-100 transform rotate-1 rounded-lg z-0 group-hover:rotate-3 transition-transform duration-300"
              aria-hidden="true"
            ></div>
            <div className="relative z-10">
              <div className="flex items-center mb-4">
                <img
                  src="https://via.placeholder.com/40"
                  alt="Jane Smith"
                  className="w-10 h-10 rounded-full mr-4"
                />
                <div>
                  <h3 className="text-lg font-bold text-black">Jane Smith</h3>
                  <p className="text-sm text-gray-500">Environmental Advocate</p>
                </div>
              </div>
              <p className="text-gray-600">
                The battery system I purchased has been a game-changer for me. It's reliable, efficient, and has given me peace of mind during power outages.
              </p>
            </div>
          </div>

          {/* Testimonial 3 */}
          <div className="relative group bg-white shadow-lg rounded-lg p-6 transition-all duration-300 hover:shadow-2xl hover:-translate-y-2">
            <div
              className="absolute -top-2 -left-2 w-full h-full bg-orange-100 transform rotate-1 rounded-lg z-0 group-hover:rotate-3 transition-transform duration-300"
              aria-hidden="true"
            ></div>
            <div className="relative z-10">
              <div className="flex items-center mb-4">
                <img
                  src="https://via.placeholder.com/40"
                  alt="David Johnson"
                  className="w-10 h-10 rounded-full mr-4"
                />
                <div>
                  <h3 className="text-lg font-bold text-black">David Johnson</h3>
                  <p className="text-sm text-gray-500">Electric Vehicle Owner</p>
                </div>
              </div>
              <p className="text-gray-600">
                I got an EV charger installed at my home, and it has made charging my electric car so convenient. The installation was quick, and the charger works flawlessly.
              </p>
            </div>
          </div>

          {/* Testimonial 4 */}
          <div className="relative group bg-white shadow-lg rounded-lg p-6 transition-all duration-300 hover:shadow-2xl hover:-translate-y-2">
            <div
              className="absolute -top-2 -left-2 w-full h-full bg-orange-100 transform rotate-1 rounded-lg z-0 group-hover:rotate-3 transition-transform duration-300"
              aria-hidden="true"
            ></div>
            <div className="relative z-10">
              <div className="flex items-center mb-4">
                <img
                  src="https://via.placeholder.com/40"
                  alt="Sarah Lee"
                  className="w-10 h-10 rounded-full mr-4"
                />
                <div>
                  <h3 className="text-lg font-bold text-black">Sarah Lee</h3>
                  <p className="text-sm text-gray-500">Renewable Energy Enthusiast</p>
                </div>
              </div>
              <p className="text-gray-600">
                I highly recommend this company for all your home energy needs. Their products are top-notch, and their customer service is exceptional.
              </p>
            </div>
          </div>
        </div>
      </section>


      <LandingPageFooter />






    </div>
  );
};

export default HOME;
