import React from "react";
import { useNavigate } from "react-router-dom";
import LandingPageHeader from "./LandingPageHeader"; // Import the new header component
import logo1400w from "../assets/logo 2-1400w.png";
import solar500w from "../assets/solar system image-500w.png"
import solar1400w from "../assets/solar system image-1400w.png"
import battery1400w from "../assets/battery system - upload seperate imagefor each option - not one file for all-1400w.png"
import evCharger1400w from "../assets/ev charger - smart charger-1400w.jpg"


const HOME = () => {
  const navigate = useNavigate();

  const handleOrderNowClick = () => {
    navigate("/product");
  };

  return (
    <div className="flex flex-col min-h-screen w-full bg-white">
      {/* Use the LandingPageHeader component */}
      <LandingPageHeader />

      {/* HERO SECTION */}
      <section className="bg-white text-center py-10 md:py-16 px-4">
        <div className="max-w-2xl mx-auto">
          <img src={logo1400w} alt="" />
          <h1 className="text-3xl md:text-3xl font-bold mb-4 py-4 leading-tight">
            Simplifying Your Future Energy Needs
          </h1>
          <p className="text-lg text-gray-600 mb-6">
            Order solar panels, batteries, and EV chargers with ease to power
            your home sustainably.
          </p>
          <button
            onClick={handleOrderNowClick}
            className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded-full font-semibold transition-colors"
          >
            ORDER NOW
          </button>
        </div>
      </section>

      {/* ORANGE SEPARATOR BAR */}
      <div
        className="w-full h-32 bg-gradient-to-b from-orange-500 to-orange-600 border-t-[12px] border-b-[12px] border-amber-900 shadow-[inset_0_2px_4px_rgba(0,0,0,0.2)]"
      ></div>


      {/* WHAT WE DO */}
      <section className="py-10 md:py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-start mb-8 text-orange-700">
            WHAT WE DO
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Card 1 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={solar500w}
                alt="Solar Panels"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Solar Panels Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Efficient solar panels installed to harness the power of the sun
                and reduce your reliance on traditional electricity sources.
              </p>
            </div>
            {/* Card 2 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={battery1400w}
                alt="Battery Storage"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                Battery Storage Solutions
              </h3>
              <p className="text-gray-600 max-w-sm">
                Store excess energy generated by your solar panels for use
                during peak hours or in case of power outages.
              </p>
            </div>
            {/* Card 3 */}
            <div className="flex flex-col items-center text-center">
              <img
                src={evCharger1400w}
                alt="EV Charger"
                className="w-[100%] h-[100%] object-cover mb-4"
              />
              <h3 className="text-xl font-semibold mb-2">
                EV Charger Installation
              </h3>
              <p className="text-gray-600 max-w-sm">
                Charge your electric vehicle at home with our EV charger
                installation services, making sustainable transportation even
                more convenient.
              </p>
            </div>
          </div>
        </div>
      </section>


      {/* HOW WE DO IT */}
      <section className="py-10 md:py-16 px-4 text-orange-700 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-6">
            HOW WE DO IT
          </h2>
          <div className="flex flex-col md:flex-row md:justify-between md:items-center mb-8">
            <p className="text-gray-600 md:w-1/2 mb-4 md:mb-0 text-center md:text-left">
              Discover the power of our straightforward system
            </p>
            <div className="text-center md:text-start">
              <button
                onClick={handleOrderNowClick}
                className="bg-orange-500 hover:bg-orange-600 text-white px-4 py-2 rounded font-semibold transition-colors"
              >
                ORDER NOW
              </button>
            </div>
          </div>

          {/* Steps Container */}
          <div className="space-y-10">
            {/* Step 1 */}
            <div className="relative p-6 bg-white shadow-md rounded-md border-l-4 border-orange-500 transform rotate-3">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                01
              </div>
              <h3 className="text-xl font-semibold mb-2">SELECTION</h3>
              <p className="text-gray-600">
                Configure your system in our tool under "Order Now". Select the
                options that suit your needs.
              </p>
            </div>
            {/* Step 2 */}
            <div className="relative p-6 bg-orange-100 shadow-md rounded-md border-l-4 border-orange-500 transform -rotate-3">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                02
              </div>
              <h3 className="text-xl font-semibold mb-2">DEPOSIT &amp; SCHEDULE</h3>
              <p className="text-gray-600">
                Our professional team will handle the installation of solar panels,
                batteries, and EV chargers at your convenience, ensuring a seamless
                setup process.
              </p>
            </div>
            {/* Step 3 */}
            <div className="relative p-6 bg-white shadow-md rounded-md border-l-4 border-orange-500 transform rotate-3">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                03
              </div>
              <h3 className="text-xl font-semibold mb-2">DESIGN CONFIRMATION</h3>
              <p className="text-gray-600">
                Once installed, we will activate your solar panels, batteries, and EV
                chargers to start harnessing clean energy for your home.
              </p>
            </div>
            {/* Step 4 */}
            <div className="relative p-6 bg-orange-100 shadow-md rounded-md border-l-4 border-orange-500 transform -rotate-3">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                04
              </div>
              <h3 className="text-xl font-semibold mb-2">INSTALLATION</h3>
              <p className="text-gray-600">
                Professional installation of selected products by certified
                technicians to ensure optimal performance.
              </p>
            </div>
            {/* Step 5 */}
            <div className="relative p-6 bg-white shadow-md rounded-md border-l-4 border-orange-500 transform rotate-3">
              <div className="absolute top-2 right-2 text-orange-600 text-2xl font-bold">
                05
              </div>
              <h3 className="text-xl font-semibold mb-2">ENJOY THE SAVINGS</h3>
              <p className="text-gray-600">
                Start enjoying the benefits of clean energy and savings on your
                electricity bills.
              </p>
            </div>
          </div>
        </div>
      </section>




      {/* CTA BANNER */}
      <section className="bg-orange-500 text-white text-center py-8 px-4">
        <div className="max-w-5xl mx-auto">
          <h3 className="text-2xl md:text-3xl font-bold mb-3">
            READY TO SIMPLIFY YOUR HOME ENERGY NEEDS?
          </h3>
          <p className="mb-5 max-w-3xl mx-auto">
            Explore our range of products and services to start saving energy and
            money today.
          </p>
          <button
            onClick={handleOrderNowClick}
            className="bg-white text-orange-600 font-semibold px-6 py-3 rounded hover:bg-orange-100 transition-colors"
          >
            ORDER NOW
          </button>
        </div>
      </section>
    </div>
  );
};

export default HOME;
